// src/views/DashboardPage.vue
<template>
  <div class="dashboard">
    <div class="page-header">
      <h2>Dashboard</h2>
      <p>Ringkasan aktivitas toko hari ini</p>
    </div>
    
    <div class="stats-grid">
      <div v-for="stat in stats" :key="stat.label" class="stat-card">
        <div class="stat-icon" :style="{ background: stat.iconBg, color: stat.iconColor }">
          <i :class="'fas ' + stat.icon"></i>
        </div>
        <p class="stat-label">{{ stat.label }}</p>
        <p class="stat-value">{{ stat.value }}</p>
      </div>
    </div>
    
    <div class="dashboard-grid">
      <div class="card">
        <h3><i class="fas fa-chart-bar"></i> Penjualan Hari Ini</h3>
        <div v-if="Object.keys(salesByHour).length === 0" class="empty-state">
          <i class="fas fa-chart-bar"></i>
          <p>Belum ada penjualan hari ini</p>
        </div>
        <div v-else class="chart-container">
          <div v-for="hour in chartHours" :key="hour" class="chart-bar">
            <div 
              class="bar"
              :style="{ height: getBarHeight(hour) + '%' }"
              :title="hour + ':00 - ' + formatRupiah(salesByHour[hour] || 0)"
            ></div>
            <span class="hour-label">{{ hour }}</span>
          </div>
        </div>
      </div>
      
      <div class="card">
        <h3><i class="fas fa-trophy"></i> Produk Terlaris</h3>
        <div v-if="topProducts.length === 0" class="empty-state">
          <i class="fas fa-box"></i>
          <p>Belum ada data</p>
        </div>
        <div v-else class="top-products">
          <div v-for="(product, i) in topProducts" :key="i" class="product-item">
            <div class="rank" :style="{ background: getRankColor(i) }">{{ i + 1 }}</div>
            <div class="product-info">
              <p class="product-name">{{ product.name }}</p>
              <p class="product-qty">{{ product.qty }} terjual</p>
            </div>
            <p class="product-revenue">{{ formatRupiah(product.revenue) }}</p>
          </div>
        </div>
      </div>
    </div>
    
    <div class="dashboard-grid">
      <div class="card">
        <h3><i class="fas fa-exclamation-triangle"></i> Stok Menipis</h3>
        <div v-if="lowStockProducts.length === 0" class="empty-state">
          <i class="fas fa-check-circle" style="color: #86efac;"></i>
          <p>Semua stok aman</p>
        </div>
        <div v-else class="stock-list">
          <div v-for="product in lowStockProducts" :key="product.id" class="stock-item">
            <div class="stock-icon" :class="product.stock === 0 ? 'danger' : 'warning'">
              <i :class="'fas ' + (product.stock === 0 ? 'fa-times-circle' : 'fa-exclamation')"></i>
            </div>
            <div class="stock-info">
              <p class="stock-name">{{ product.name }}</p>
              <div class="stock-bar">
                <div 
                  class="bar-fill"
                  :style="{ 
                    width: Math.min((product.stock / product.minStock) * 100, 100) + '%',
                    background: (product.stock / product.minStock) <= 0.3 ? '#dc2626' : '#eab308'
                  }"
                ></div>
              </div>
              <span class="stock-count">{{ product.stock }}/{{ product.minStock }}</span>
            </div>
          </div>
        </div>
      </div>
      
      <div class="card">
        <h3><i class="fas fa-clock-rotate-left"></i> Transaksi Terakhir</h3>
        <div v-if="recentTransactions.length === 0" class="empty-state">
          <i class="fas fa-receipt"></i>
          <p>Belum ada transaksi</p>
        </div>
        <div v-else class="transaction-list">
          <div v-for="t in recentTransactions" :key="t.id" class="transaction-item">
            <div class="transaction-icon">
              <i class="fas fa-receipt"></i>
            </div>
            <div class="transaction-info">
              <p class="transaction-invoice">{{ t.invoiceNo }}</p>
              <p class="transaction-time">{{ formatTime(t.date) }}</p>
            </div>
            <div class="transaction-amount">
              <p class="amount">{{ formatRupiah(t.total) }}</p>
              <p class="method">{{ t.paymentMethod }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'DashboardPage',
  computed: {
    stats() {
      const today = new Date().toDateString()
      const todaySales = this.$store.state.salesTransactions.filter(t => 
        new Date(t.date).toDateString() === today
      )
      const totalSales = this.$store.state.salesTransactions.reduce((s, t) => s + t.total, 0)
      const todayTotal = todaySales.reduce((s, t) => s + t.total, 0)
      const cogs = this.$store.state.salesTransactions.reduce((s, t) => 
        s + t.items.reduce((is, i) => is + i.product.buyPrice * i.quantity, 0), 0
      )
      const netProfit = totalSales - cogs - this.$store.state.expenses.reduce((s, e) => s + e.amount, 0)
      const lowStock = this.$store.state.products.filter(p => p.stock <= p.minStock).length
      const totalStock = this.$store.state.products.reduce((s, p) => s + p.stock, 0)
      
      return [
        { label: 'Penjualan Hari Ini', value: this.formatRupiah(todayTotal), icon: 'fa-coins', iconBg: '#dcfce7', iconColor: '#16a34a' },
        { label: 'Total Transaksi', value: this.$store.state.salesTransactions.length.toString(), icon: 'fa-receipt', iconBg: '#dbeafe', iconColor: '#2563eb' },
        { label: 'Keuntungan', value: this.formatRupiah(netProfit), icon: 'fa-sack-dollar', iconBg: '#d1fae5', iconColor: '#059669' },
        { label: 'Pembelian', value: this.formatRupiah(this.$store.state.purchaseOrders.reduce((s, p) => s + p.total, 0)), icon: 'fa-truck', iconBg: '#ffedd5', iconColor: '#ea580c' },
        { label: 'Stok Produk', value: totalStock.toLocaleString(), icon: 'fa-cubes', iconBg: '#f3e8ff', iconColor: '#7c3aed' },
        { label: 'Stok Menipis', value: lowStock.toString(), icon: 'fa-exclamation-triangle', iconBg: '#fee2e2', iconColor: '#dc2626' }
      ]
    },
    salesByHour() {
      const today = new Date().toDateString()
      const result = {}
      this.$store.state.salesTransactions
        .filter(t => new Date(t.date).toDateString() === today)
        .forEach(t => {
          const h = new Date(t.date).getHours()
          result[h] = (result[h] || 0) + t.total
        })
      return result
    },
    chartHours() {
      return Array.from({ length: 14 }, (_, i) => i + 7)
    },
    topProducts() {
      const sales = {}
      this.$store.state.salesTransactions.forEach(t => {
        t.items.forEach(item => {
          if (!sales[item.product.id]) {
            sales[item.product.id] = { name: item.product.name, qty: 0, revenue: 0 }
          }
          sales[item.product.id].qty += item.quantity
          sales[item.product.id].revenue += item.subtotal
        })
      })
      return Object.values(sales).sort((a, b) => b.qty - a.qty).slice(0, 5)
    },
    lowStockProducts() {
      return this.$store.state.products
        .filter(p => p.stock <= p.minStock)
        .sort((a, b) => (a.stock / a.minStock) - (b.stock / b.minStock))
        .slice(0, 5)
    },
    recentTransactions() {
      return this.$store.state.salesTransactions.slice(0, 5)
    }
  },
  methods: {
    formatRupiah(n) {
      return 'Rp ' + (n || 0).toLocaleString('id-ID')
    },
    formatTime(date) {
      return new Date(date).toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' })
    },
    getBarHeight(hour) {
      const max = Math.max(...Object.values(this.salesByHour), 1)
      return ((this.salesByHour[hour] || 0) / max) * 100
    },
    getRankColor(i) {
      const colors = ['#eab308', '#9ca3af', '#fb923c', '#d1d5db']
      return colors[i] || colors[3]
    }
  }
}
</script>

<style scoped>
.dashboard {
  padding: 1.5rem;
  max-width: 1200px;
  margin: 0 auto;
}

.page-header {
  margin-bottom: 1.5rem;
}

.page-header h2 {
  font-size: 1.25rem;
  font-weight: 700;
  color: #1f2937;
  margin-bottom: 0.25rem;
}

.page-header p {
  font-size: 0.875rem;
  color: #6b7280;
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
  gap: 0.75rem;
  margin-bottom: 1.5rem;
}

.stat-card {
  background: white;
  border-radius: 0.75rem;
  padding: 1rem;
  border: 1px solid #e5e7eb;
}

.stat-icon {
  width: 2.5rem;
  height: 2.5rem;
  border-radius: 0.5rem;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 0.5rem;
}

.stat-label {
  font-size: 0.75rem;
  color: #6b7280;
  margin-bottom: 0.25rem;
}

.stat-value {
  font-size: 1rem;
  font-weight: 700;
  color: #1f2937;
}

.dashboard-grid {
  display: grid;
  grid-template-columns: 2fr 1fr;
  gap: 1rem;
  margin-bottom: 1rem;
}

.card {
  background: white;
  border-radius: 0.75rem;
  border: 1px solid #e5e7eb;
  padding: 1rem;
}

.card h3 {
  font-weight: 700;
  font-size: 0.875rem;
  color: #1f2937;
  margin-bottom: 1rem;
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.empty-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 10rem;
  color: #9ca3af;
}

.empty-state i {
  font-size: 2rem;
  margin-bottom: 0.75rem;
  opacity: 0.3;
}

.empty-state p {
  font-size: 0.875rem;
}

.chart-container {
  display: flex;
  align-items: flex-end;
  gap: 2px;
  height: 8rem;
}

.chart-bar {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 2px;
}

.bar {
  width: 100%;
  background: linear-gradient(to top, #3b82f6, #60a5fa);
  border-radius: 2px 2px 0 0;
  min-height: 2px;
}

.hour-label {
  font-size: 0.55rem;
  color: #9ca3af;
}

.top-products {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.product-item {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.rank {
  width: 1.5rem;
  height: 1.5rem;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 0.65rem;
  font-weight: 700;
  color: white;
}

.product-info {
  flex: 1;
  min-width: 0;
}

.product-name {
  font-size: 0.75rem;
  font-weight: 500;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.product-qty {
  font-size: 0.65rem;
  color: #6b7280;
}

.product-revenue {
  font-size: 0.65rem;
  font-weight: 700;
  color: #2563eb;
}

.stock-list {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.stock-item {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.4rem;
  background: #f9fafb;
  border-radius: 0.5rem;
}

.stock-icon {
  width: 2rem;
  height: 2rem;
  border-radius: 0.5rem;
  display: flex;
  align-items: center;
  justify-content: center;
}

.stock-icon.warning {
  background: #fef9c3;
  color: #ca8a04;
}

.stock-icon.danger {
  background: #fee2e2;
  color: #dc2626;
}

.stock-info {
  flex: 1;
  min-width: 0;
}

.stock-name {
  font-size: 0.75rem;
  font-weight: 500;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  margin-bottom: 0.2rem;
}

.stock-bar {
  flex: 1;
  height: 0.3rem;
  background: #e5e7eb;
  border-radius: 9999px;
  overflow: hidden;
  margin-bottom: 0.2rem;
}

.bar-fill {
  height: 100%;
  border-radius: 9999px;
}

.stock-count {
  font-size: 0.6rem;
  color: #6b7280;
}

.transaction-list {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.transaction-item {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.4rem;
  border-radius: 0.5rem;
}

.transaction-icon {
  width: 2rem;
  height: 2rem;
  background: #dbeafe;
  border-radius: 0.5rem;
  display: flex;
  align-items: center;
  justify-content: center;
}

.transaction-icon i {
  font-size: 0.6rem;
  color: #2563eb;
}

.transaction-info {
  flex: 1;
  min-width: 0;
}

.transaction-invoice {
  font-size: 0.75rem;
  font-weight: 500;
}

.transaction-time {
  font-size: 0.6rem;
  color: #6b7280;
}

.transaction-amount {
  text-align: right;
}

.amount {
  font-size: 0.75rem;
  font-weight: 700;
  color: #16a34a;
}

.method {
  font-size: 0.6rem;
  color: #9ca3af;
}

@media (max-width: 768px) {
  .dashboard-grid {
    grid-template-columns: 1fr;
  }
}
</style>

// src/pages/DashboardPage.tsx
import React, { useMemo } from 'react';
import { useStore } from '../context/StoreContext';

export default function DashboardPage() {
  const { products, salesTransactions, purchaseOrders, expenses } = useStore();

  const stats = useMemo(() => {
    const today = new Date().toDateString();
    const todaySales = salesTransactions.filter(t => new Date(t.date).toDateString() === today);
    const totalSales = salesTransactions.reduce((s, t) => s + t.total, 0);
    const todayTotal = todaySales.reduce((s, t) => s + t.total, 0);
    const cogs = salesTransactions.reduce((s, t) => s + t.items.reduce((is, i) => is + i.product.buyPrice * i.quantity, 0), 0);
    const netProfit = totalSales - cogs - expenses.reduce((s, e) => s + e.amount, 0);
    const lowStock = products.filter(p => p.stock <= p.minStock).length;
    const totalStock = products.reduce((s, p) => s + p.stock, 0);

    return [
      { label: 'Penjualan Hari Ini', value: formatRupiah(todayTotal), icon: 'fa-coins', iconBg: 'bg-green-100', iconColor: 'text-green-600' },
      { label: 'Total Transaksi', value: salesTransactions.length.toString(), icon: 'fa-receipt', iconBg: 'bg-blue-100', iconColor: 'text-blue-600' },
      { label: 'Keuntungan', value: formatRupiah(netProfit), icon: 'fa-sack-dollar', iconBg: 'bg-emerald-100', iconColor: 'text-emerald-600' },
      { label: 'Pembelian', value: formatRupiah(purchaseOrders.reduce((s, p) => s + p.total, 0)), icon: 'fa-truck', iconBg: 'bg-orange-100', iconColor: 'text-orange-600' },
      { label: 'Stok Produk', value: totalStock.toLocaleString(), icon: 'fa-cubes', iconBg: 'bg-purple-100', iconColor: 'text-purple-600' },
      { label: 'Stok Menipis', value: lowStock.toString(), icon: 'fa-exclamation-triangle', iconBg: 'bg-red-100', iconColor: 'text-red-600' },
    ];
  }, [products, salesTransactions, purchaseOrders, expenses]);

  const salesByHour = useMemo(() => {
    const today = new Date().toDateString();
    const result: Record<number, number> = {};
    salesTransactions.filter(t => new Date(t.date).toDateString() === today).forEach(t => {
      const h = new Date(t.date).getHours();
      result[h] = (result[h] || 0) + t.total;
    });
    return result;
  }, [salesTransactions]);

  const chartHours = Array.from({ length: 14 }, (_, i) => i + 7);
  const maxHourlySales = Math.max(...Object.values(salesByHour), 1);

  const topProducts = useMemo(() => {
    const sales: Record<string, { name: string; qty: number; revenue: number }> = {};
    salesTransactions.forEach(t => {
      t.items.forEach(item => {
        if (!sales[item.product.id]) sales[item.product.id] = { name: item.product.name, qty: 0, revenue: 0 };
        sales[item.product.id].qty += item.quantity;
        sales[item.product.id].revenue += item.subtotal;
      });
    });
    return Object.values(sales).sort((a, b) => b.qty - a.qty).slice(0, 5);
  }, [salesTransactions]);

  const lowStockProducts = useMemo(() => {
    return products.filter(p => p.stock <= p.minStock).sort((a, b) => (a.stock / a.minStock) - (b.stock / b.minStock)).slice(0, 5);
  }, [products]);

  const recentTransactions = salesTransactions.slice(0, 5);

  function formatRupiah(n: number) {
    return 'Rp ' + (n || 0).toLocaleString('id-ID');
  }

  function getRankColor(i: number) {
    const colors = ['bg-yellow-500', 'bg-gray-400', 'bg-orange-400', 'bg-gray-300'];
    return colors[i] || colors[3];
  }

  return (
    <div className="h-full overflow-y-auto p-4 lg:p-6">
      <div className="max-w-7xl mx-auto">
        <div className="mb-5">
          <h2 className="text-xl font-bold text-gray-800">Dashboard</h2>
          <p className="text-sm text-gray-500">Ringkasan aktivitas toko hari ini</p>
        </div>

        {/* Stats Grid */}
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3 mb-6">
          {stats.map((stat, i) => (
            <div key={i} className="bg-white rounded-xl p-4 shadow-sm border border-gray-100 hover:shadow-md transition-shadow">
              <div className={`w-10 h-10 rounded-lg ${stat.iconBg} ${stat.iconColor} flex items-center justify-center mb-3`}>
                <i className={`fas ${stat.icon}`}></i>
              </div>
              <p className="text-xs text-gray-500 mb-1">{stat.label}</p>
              <p className="text-base font-bold text-gray-800 truncate">{stat.value}</p>
            </div>
          ))}
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 mb-6">
          {/* Sales by Hour Chart */}
          <div className="lg:col-span-2 bg-white rounded-xl shadow-sm border border-gray-100 p-4">
            <h3 className="font-bold text-gray-800 mb-4 flex items-center gap-2">
              <i className="fas fa-chart-bar text-blue-500"></i>
              Penjualan Hari Ini
            </h3>
            {Object.keys(salesByHour).length === 0 ? (
              <div className="flex flex-col items-center justify-center h-48 text-gray-400">
                <i className="fas fa-chart-bar text-4xl mb-3 opacity-30"></i>
                <p className="text-sm">Belum ada penjualan hari ini</p>
              </div>
            ) : (
              <div className="flex items-end gap-1 h-40">
                {chartHours.map(hour => {
                  const value = salesByHour[hour] || 0;
                  const height = (value / maxHourlySales) * 100;
                  return (
                    <div key={hour} className="flex-1 flex flex-col items-center gap-1">
                      <div className="w-full flex flex-col items-center justify-end h-32">
                        <div
                          className="w-full bg-gradient-to-t from-blue-500 to-blue-400 rounded-t-sm transition-all hover:from-blue-600 hover:to-blue-500"
                          style={{ height: `${Math.max(height, 2)}%` }}
                          title={`${hour}:00 - ${formatRupiah(value)}`}
                        ></div>
                      </div>
                      <span className="text-[9px] text-gray-400">{hour}</span>
                    </div>
                  );
                })}
              </div>
            )}
          </div>

          {/* Top Products */}
          <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-4">
            <h3 className="font-bold text-gray-800 mb-4 flex items-center gap-2">
              <i className="fas fa-trophy text-yellow-500"></i>
              Produk Terlaris
            </h3>
            {topProducts.length === 0 ? (
              <div className="flex flex-col items-center justify-center h-48 text-gray-400">
                <i className="fas fa-box text-4xl mb-3 opacity-30"></i>
                <p className="text-sm">Belum ada data</p>
              </div>
            ) : (
              <div className="space-y-3">
                {topProducts.map((product, i) => (
                  <div key={i} className="flex items-center gap-3">
                    <span className={`w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold text-white ${getRankColor(i)}`}>
                      {i + 1}
                    </span>
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium truncate">{product.name}</p>
                      <p className="text-xs text-gray-500">{product.qty} terjual</p>
                    </div>
                    <p className="text-xs font-bold text-blue-600">{formatRupiah(product.revenue)}</p>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          {/* Low Stock Alert */}
          <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-4">
            <h3 className="font-bold text-gray-800 mb-4 flex items-center gap-2">
              <i className="fas fa-exclamation-triangle text-red-500"></i>
              Stok Menipis
            </h3>
            {lowStockProducts.length === 0 ? (
              <div className="flex flex-col items-center justify-center h-40 text-gray-400">
                <i className="fas fa-check-circle text-4xl mb-3 opacity-30 text-green-300"></i>
                <p className="text-sm">Semua stok aman</p>
              </div>
            ) : (
              <div className="space-y-2">
                {lowStockProducts.map(product => {
                  const percentage = (product.stock / product.minStock) * 100;
                  return (
                    <div key={product.id} className="flex items-center gap-3 p-2 rounded-lg bg-gray-50">
                      <div className={`w-8 h-8 rounded-lg flex items-center justify-center ${
                        product.stock === 0 ? 'bg-red-100 text-red-600' : 'bg-yellow-100 text-yellow-600'
                      }`}>
                        <i className={`fas ${product.stock === 0 ? 'fa-times-circle' : 'fa-exclamation'}`}></i>
                      </div>
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium truncate">{product.name}</p>
                        <div className="flex items-center gap-2 mt-1">
                          <div className="flex-1 h-1.5 bg-gray-200 rounded-full overflow-hidden">
                            <div className={`h-full rounded-full ${percentage <= 30 ? 'bg-red-500' : 'bg-yellow-500'}`} style={{ width: `${Math.min(percentage, 100)}%` }}></div>
                          </div>
                          <span className="text-xs text-gray-500">{product.stock}/{product.minStock}</span>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>

          {/* Recent Transactions */}
          <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-4">
            <h3 className="font-bold text-gray-800 mb-4 flex items-center gap-2">
              <i className="fas fa-clock-rotate-left text-gray-500"></i>
              Transaksi Terakhir
            </h3>
            {recentTransactions.length === 0 ? (
              <div className="flex flex-col items-center justify-center h-40 text-gray-400">
                <i className="fas fa-receipt text-4xl mb-3 opacity-30"></i>
                <p className="text-sm">Belum ada transaksi</p>
              </div>
            ) : (
              <div className="space-y-2">
                {recentTransactions.map(t => (
                  <div key={t.id} className="flex items-center gap-3 p-2 rounded-lg hover:bg-gray-50">
                    <div className="w-8 h-8 bg-blue-100 rounded-lg flex items-center justify-center">
                      <i className="fas fa-receipt text-blue-600 text-xs"></i>
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium">{t.invoiceNo}</p>
                      <p className="text-xs text-gray-500">{new Date(t.date).toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' })}</p>
                    </div>
                    <div className="text-right">
                      <p className="text-sm font-bold text-green-600">{formatRupiah(t.total)}</p>
                      <p className="text-xs text-gray-400">{t.paymentMethod}</p>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
