// src/views/POSPage.vue
<template>
  <div class="pos-page">
    <div class="pos-layout">
      <!-- Products Section -->
      <div class="pos-products">
        <div class="pos-header">
          <div class="search-box">
            <i class="fas fa-search"></i>
            <input 
              v-model="search" 
              type="text" 
              placeholder="🔍 Scan barcode / Cari produk..."
            />
          </div>
          <div class="category-bar">
            <button 
              :class="['cat-btn', { active: activeCategory === 'all' }]"
              @click="activeCategory = 'all'"
            >
              <i class="fas fa-border-all"></i> Semua
            </button>
            <button 
              v-for="cat in categories" 
              :key="cat.id"
              :class="['cat-btn', { active: activeCategory === cat.id }]"
              @click="activeCategory = cat.id"
            >
              <i :class="'fas ' + cat.icon"></i> {{ cat.name }}
            </button>
          </div>
        </div>
        
        <div class="product-grid">
          <button 
            v-for="product in filteredProducts" 
            :key="product.id"
            class="product-card"
            :disabled="product.stock <= 0"
            @click="addToCart(product)"
          >
            <div 
              class="product-icon"
              :style="{ background: getCategoryColor(product.categoryId) }"
            >
              <i :class="'fas ' + getCategoryIcon(product.categoryId)"></i>
            </div>
            <h3 class="product-name">{{ product.name }}</h3>
            <p class="product-price">{{ formatRupiah(product.sellPrice) }}</p>
            <div class="product-footer">
              <span :class="['badge', getStockBadge(product)]">{{ product.stock }} {{ getUnitName(product.unitId) }}</span>
              <span class="sku">{{ product.sku }}</span>
            </div>
          </button>
        </div>
      </div>

      <!-- Cart Section -->
      <div class="pos-cart">
        <div class="cart-header">
          <div class="cart-title">
            <i class="fas fa-shopping-cart"></i>
            <h2>Keranjang</h2>
          </div>
          <span class="cart-count">{{ cartTotalItems }} item</span>
          <p class="cart-total">{{ formatRupiah(cartGrandTotal) }}</p>
        </div>
        
        <div class="customer-select">
          <select v-model="selectedCustomerId">
            <option v-for="c in customers" :key="c.id" :value="c.id">
              {{ c.name }} {{ c.isMember ? '(' + c.memberCode + ')' : '' }}
            </option>
          </select>
        </div>
        
        <div class="cart-items">
          <div v-if="cart.length === 0" class="empty-cart">
            <i class="fas fa-cart-shopping"></i>
            <p>Keranjang kosong</p>
            <small>Klik produk untuk menambahkan</small>
          </div>
          <div v-else class="cart-list">
            <div v-for="item in cart" :key="item.product.id" class="cart-item">
              <div class="item-header">
                <div class="item-info">
                  <h4>{{ item.product.name }}</h4>
                  <p>{{ formatRupiah(item.product.sellPrice) }} × {{ item.quantity }}</p>
                </div>
                <button @click="removeFromCart(item.product.id)" class="remove-btn">
                  <i class="fas fa-trash"></i>
                </button>
              </div>
              <div class="item-footer">
                <div class="qty-controls">
                  <button @click="updateCartQty(item.product.id, -1)">−</button>
                  <span>{{ item.quantity }}</span>
                  <button @click="updateCartQty(item.product.id, 1)" :disabled="item.quantity >= item.product.stock">+</button>
                </div>
                <p class="item-subtotal">{{ formatRupiah(item.product.sellPrice * item.quantity) }}</p>
              </div>
            </div>
          </div>
        </div>
        
        <div class="cart-footer">
          <div class="summary-row">
            <span>Subtotal</span>
            <span>{{ formatRupiah(cartSubtotal) }}</span>
          </div>
          <div class="summary-row">
            <span>PPN ({{ storeSettings.taxRate }}%)</span>
            <span>{{ formatRupiah(cartTax) }}</span>
          </div>
          <div class="summary-row total">
            <span>TOTAL</span>
            <span>{{ formatRupiah(cartGrandTotal) }}</span>
          </div>
          <div class="cart-actions">
            <button @click="clearCart" :disabled="cart.length === 0" class="btn-cancel">
              <i class="fas fa-times"></i> Batal
            </button>
            <button @click="showPaymentModal = true" :disabled="cart.length === 0" class="btn-pay">
              <i class="fas fa-credit-card"></i> BAYAR
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Payment Modal -->
    <div v-if="showPaymentModal" class="modal-overlay" @click.self="showPaymentModal = false">
      <div class="modal-box">
        <div class="modal-header">
          <h2><i class="fas fa-cash-register"></i> Pembayaran</h2>
          <button @click="showPaymentModal = false" class="close-btn">
            <i class="fas fa-times"></i>
          </button>
        </div>
        <div class="modal-body">
          <div class="payment-total">
            <p>Total Pembayaran</p>
            <p class="amount">{{ formatRupiah(cartGrandTotal) }}</p>
          </div>
          <div class="payment-methods">
            <button 
              v-for="pm in paymentMethods.filter(p => p.active)" 
              :key="pm.id"
              @click="paymentMethod = pm.name"
              :class="['method-btn', { active: paymentMethod === pm.name }]"
            >
              <i :class="'fas ' + pm.icon"></i>
              {{ pm.name }}
            </button>
          </div>
          <div v-if="paymentMethod === 'Tunai'" class="cash-input">
            <div class="input-wrapper">
              <span>Rp</span>
              <input 
                v-model="cashInput" 
                type="text" 
                placeholder="0"
              />
            </div>
            <div v-if="cashValue > 0" :class="['change-box', cashChange >= 0 ? 'success' : 'danger']">
              <p>Kembalian</p>
              <p class="amount">{{ cashChange >= 0 ? formatRupiah(cashChange) : 'Kurang ' + formatRupiah(Math.abs(cashChange)) }}</p>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button @click="showPaymentModal = false" class="btn-cancel">Batal</button>
          <button @click="processPayment" :disabled="!isPaymentValid" class="btn-process">
            <i class="fas fa-check-circle"></i> Proses Pembayaran
          </button>
        </div>
      </div>
    </div>

    <!-- Receipt Modal -->
    <div v-if="showReceiptModal && lastTransaction" class="modal-overlay" @click.self="showReceiptModal = false">
      <div class="modal-box receipt-modal">
        <div class="receipt-header">
          <div class="success-icon">
            <i class="fas fa-check"></i>
          </div>
          <h2>Transaksi Berhasil!</h2>
        </div>
        <div class="receipt-body">
          <div class="receipt">
            <div class="receipt-store">
              <p class="store-name">{{ storeSettings.name }}</p>
              <p class="store-address">{{ storeSettings.address }}</p>
            </div>
            <div class="receipt-info">
              <div class="info-row">
                <span>No:</span>
                <span>{{ lastTransaction.invoiceNo }}</span>
              </div>
              <div class="info-row">
                <span>Kasir:</span>
                <span>{{ lastTransaction.cashierName }}</span>
              </div>
            </div>
            <div class="receipt-items">
              <div v-for="item in lastTransaction.items" :key="item.product.id" class="receipt-item">
                <p class="item-name">{{ item.product.name }}</p>
                <div class="item-detail">
                  <span>{{ item.quantity }} x {{ formatRupiah(item.product.sellPrice) }}</span>
                  <span>{{ formatRupiah(item.product.sellPrice * item.quantity) }}</span>
                </div>
              </div>
            </div>
            <div class="receipt-total">
              <div class="total-row">
                <span>TOTAL:</span>
                <span>{{ formatRupiah(lastTransaction.total) }}</span>
              </div>
            </div>
            <div class="receipt-payment">
              <div class="payment-row">
                <span>Bayar ({{ lastTransaction.paymentMethod }}):</span>
                <span>{{ formatRupiah(lastTransaction.paymentAmount) }}</span>
              </div>
              <div v-if="lastTransaction.change > 0" class="payment-row">
                <span>Kembali:</span>
                <span>{{ formatRupiah(lastTransaction.change) }}</span>
              </div>
            </div>
            <div class="receipt-footer">
              <p>Terima kasih atas kunjungan Anda</p>
            </div>
          </div>
        </div>
        <div class="receipt-actions">
          <button @click="newTransaction" class="btn-new">
            <i class="fas fa-plus"></i> Transaksi Baru
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'POSPage',
  data() {
    return {
      search: '',
      activeCategory: 'all',
      cart: [],
      selectedCustomerId: 'c0',
      showPaymentModal: false,
      paymentMethod: 'Tunai',
      cashInput: '',
      showReceiptModal: false,
      lastTransaction: null
    }
  },
  computed: {
    categories() {
      return this.$store.state.categories
    },
    customers() {
      return this.$store.state.customers
    },
    paymentMethods() {
      return this.$store.state.paymentMethods
    },
    storeSettings() {
      return this.$store.state.storeSettings
    },
    filteredProducts() {
      return this.$store.state.products.filter(p => {
        if (p.status !== 'active') return false
        const matchCat = this.activeCategory === 'all' || p.categoryId === this.activeCategory
        const matchSearch = p.name.toLowerCase().includes(this.search.toLowerCase()) ||
          p.barcode.includes(this.search) ||
          p.sku.toLowerCase().includes(this.search.toLowerCase())
        return matchCat && matchSearch
      })
    },
    cartTotalItems() {
      return this.cart.reduce((s, i) => s + i.quantity, 0)
    },
    cartSubtotal() {
      return this.cart.reduce((s, i) => s + i.product.sellPrice * i.quantity, 0)
    },
    cartTax() {
      return Math.round(this.cartSubtotal * (this.storeSettings.taxRate / 100))
    },
    cartGrandTotal() {
      return this.cartSubtotal + this.cartTax
    },
    cashValue() {
      return parseInt(String(this.cashInput).replace(/\D/g, '')) || 0
    },
    cashChange() {
      return this.cashValue - this.cartGrandTotal
    },
    isPaymentValid() {
      if (this.paymentMethod === 'Tunai') return this.cashValue >= this.cartGrandTotal
      return true
    }
  },
  methods: {
    formatRupiah(n) {
      return 'Rp ' + (n || 0).toLocaleString('id-ID')
    },
    getCategoryIcon(id) {
      const cat = this.$store.state.categories.find(c => c.id === id)
      return cat ? cat.icon : 'fa-box'
    },
    getCategoryColor(id) {
      const cat = this.$store.state.categories.find(c => c.id === id)
      return cat ? cat.color : '#f3f4f6'
    },
    getUnitName(id) {
      const unit = this.$store.state.units.find(u => u.id === id)
      return unit ? unit.shortName : '-'
    },
    getStockBadge(product) {
      if (product.stock === 0) return 'badge-red'
      if (product.stock <= product.minStock) return 'badge-yellow'
      return 'badge-green'
    },
    addToCart(product) {
      if (product.stock <= 0) return
      const existing = this.cart.find(i => i.product.id === product.id)
      if (existing) {
        if (existing.quantity < product.stock) existing.quantity++
      } else {
        this.cart.push({ product: JSON.parse(JSON.stringify(product)), quantity: 1 })
      }
    },
    updateCartQty(productId, delta) {
      const item = this.cart.find(i => i.product.id === productId)
      if (!item) return
      const newQty = item.quantity + delta
      if (newQty <= 0) {
        this.removeFromCart(productId)
        return
      }
      if (newQty > item.product.stock) return
      item.quantity = newQty
    },
    removeFromCart(productId) {
      this.cart = this.cart.filter(i => i.product.id !== productId)
    },
    clearCart() {
      this.cart = []
    },
    processPayment() {
      if (!this.isPaymentValid) return
      const change = this.paymentMethod === 'Tunai' ? this.cashChange : 0
      const payment = this.paymentMethod === 'Tunai' ? this.cashValue : this.cartGrandTotal
      const transaction = {
        id: 'TX-' + Date.now(),
        invoiceNo: 'INV-' + String(Date.now()).slice(-6),
        items: JSON.parse(JSON.stringify(this.cart)),
        subtotal: this.cartSubtotal,
        discount: 0,
        tax: this.cartTax,
        total: this.cartGrandTotal,
        paymentMethod: this.paymentMethod,
        paymentAmount: payment,
        change: change,
        customerId: this.selectedCustomerId,
        customerName: (this.customers.find(c => c.id === this.selectedCustomerId) || {}).name || 'Walk-in',
        cashierId: this.$store.state.currentUser.id,
        cashierName: this.$store.state.currentUser.name,
        date: new Date().toISOString(),
        status: 'completed',
        shiftId: this.$store.state.currentShift ? this.$store.state.currentShift.id : ''
      }
      this.$store.dispatch('addSaleTransaction', transaction)
      this.lastTransaction = transaction
      this.showPaymentModal = false
      this.showReceiptModal = true
      this.cart = []
      this.cashInput = ''
    },
    newTransaction() {
      this.showReceiptModal = false
      this.lastTransaction = null
    }
  }
}
</script>

<style scoped>
.pos-page {
  height: 100%;
  display: flex;
  flex-direction: column;
}

.pos-layout {
  display: flex;
  height: 100%;
  overflow: hidden;
}

.pos-products {
  flex: 1;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.pos-header {
  padding: 0.75rem;
  background: white;
  border-bottom: 1px solid #e5e7eb;
}

.search-box {
  position: relative;
  margin-bottom: 0.5rem;
}

.search-box i {
  position: absolute;
  left: 0.75rem;
  top: 50%;
  transform: translateY(-50%);
  color: #9ca3af;
}

.search-box input {
  width: 100%;
  padding: 0.5rem 0.75rem 0.5rem 2.5rem;
  border: 1px solid #d1d5db;
  border-radius: 0.5rem;
  font-size: 0.875rem;
  outline: none;
}

.search-box input:focus {
  border-color: #2563eb;
  box-shadow: 0 0 0 2px rgba(37, 99, 235, 0.2);
}

.category-bar {
  display: flex;
  gap: 0.4rem;
  overflow-x: auto;
  padding-bottom: 0.25rem;
}

.category-bar::-webkit-scrollbar {
  display: none;
}

.cat-btn {
  padding: 0.35rem 0.75rem;
  border-radius: 9999px;
  font-size: 0.7rem;
  font-weight: 500;
  white-space: nowrap;
  border: none;
  cursor: pointer;
  transition: all 0.2s;
}

.cat-btn.active {
  background: #2563eb;
  color: white;
}

.cat-btn:not(.active) {
  background: #f3f4f6;
  color: #4b5563;
}

.cat-btn:not(.active):hover {
  background: #e5e7eb;
}

.product-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(140px, 1fr));
  gap: 0.5rem;
  padding: 0.75rem;
  overflow-y: auto;
  flex: 1;
}

.product-card {
  background: white;
  border: 2px solid #f3f4f6;
  border-radius: 0.75rem;
  padding: 0.6rem;
  cursor: pointer;
  transition: all 0.2s;
  text-align: left;
}

.product-card:hover:not(:disabled) {
  border-color: #93c5fd;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
  transform: translateY(-2px);
}

.product-card:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.product-icon {
  width: 100%;
  aspect-ratio: 1;
  border-radius: 0.5rem;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 0.4rem;
  font-size: 1.2rem;
}

.product-name {
  font-size: 0.65rem;
  font-weight: 600;
  color: #1f2937;
  margin-bottom: 0.2rem;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
  line-height: 1.3;
}

.product-price {
  font-size: 0.8rem;
  font-weight: 700;
  color: #1d4ed8;
}

.product-footer {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-top: 0.2rem;
}

.badge {
  font-size: 0.55rem;
  padding: 0.15rem 0.5rem;
  border-radius: 9999px;
  font-weight: 600;
}

.badge-green {
  background: #dcfce7;
  color: #166534;
}

.badge-yellow {
  background: #fef9c3;
  color: #854d0e;
}

.badge-red {
  background: #fee2e2;
  color: #991b1b;
}

.sku {
  font-size: 0.55rem;
  color: #9ca3af;
}

.pos-cart {
  width: 360px;
  background: white;
  border-left: 1px solid #e5e7eb;
  display: flex;
  flex-direction: column;
  box-shadow: -4px 0 15px rgba(0, 0, 0, 0.05);
}

.cart-header {
  background: linear-gradient(to right, #2563eb, #1d4ed8);
  color: white;
  padding: 0.75rem;
}

.cart-title {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin-bottom: 0.25rem;
}

.cart-title h2 {
  font-weight: 700;
  font-size: 0.8rem;
}

.cart-count {
  background: rgba(255, 255, 255, 0.2);
  padding: 0.15rem 0.5rem;
  border-radius: 9999px;
  font-size: 0.65rem;
  display: inline-block;
  margin-bottom: 0.25rem;
}

.cart-total {
  font-size: 1.3rem;
  font-weight: 700;
}

.customer-select {
  padding: 0.5rem;
  border-bottom: 1px solid #e5e7eb;
  background: #f9fafb;
}

.customer-select select {
  width: 100%;
  padding: 0.3rem;
  font-size: 0.7rem;
  border: 1px solid #d1d5db;
  border-radius: 0.5rem;
  outline: none;
}

.cart-items {
  flex: 1;
  overflow-y: auto;
}

.empty-cart {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100%;
  color: #9ca3af;
  padding: 1.5rem;
}

.empty-cart i {
  font-size: 2.5rem;
  margin-bottom: 0.75rem;
  opacity: 0.3;
}

.empty-cart p {
  font-size: 0.75rem;
  font-weight: 500;
}

.empty-cart small {
  font-size: 0.6rem;
  margin-top: 0.25rem;
}

.cart-list {
  display: flex;
  flex-direction: column;
}

.cart-item {
  padding: 0.6rem;
  border-bottom: 1px solid #f3f4f6;
}

.item-header {
  display: flex;
  align-items: start;
  gap: 0.5rem;
  margin-bottom: 0.4rem;
}

.item-info {
  flex: 1;
  min-width: 0;
}

.item-info h4 {
  font-size: 0.7rem;
  font-weight: 500;
  color: #1f2937;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.item-info p {
  font-size: 0.6rem;
  color: #6b7280;
}

.remove-btn {
  background: none;
  border: none;
  color: #f87171;
  cursor: pointer;
  font-size: 0.6rem;
  padding: 0.2rem;
}

.item-footer {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.qty-controls {
  display: flex;
  align-items: center;
  gap: 0.25rem;
}

.qty-controls button {
  width: 1.4rem;
  height: 1.4rem;
  border-radius: 0.25rem;
  background: #f3f4f6;
  border: none;
  cursor: pointer;
  font-weight: 700;
  font-size: 0.7rem;
}

.qty-controls button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.qty-controls span {
  width: 2rem;
  text-align: center;
  font-size: 0.7rem;
  font-weight: 700;
}

.item-subtotal {
  font-size: 0.7rem;
  font-weight: 700;
  color: #1d4ed8;
}

.cart-footer {
  border-top: 1px solid #e5e7eb;
  background: #f9fafb;
  padding: 0.75rem;
}

.summary-row {
  display: flex;
  justify-content: space-between;
  font-size: 0.7rem;
  margin-bottom: 0.3rem;
}

.summary-row span:first-child {
  color: #6b7280;
}

.summary-row.total {
  font-size: 1rem;
  font-weight: 700;
  border-top: 1px solid #e5e7eb;
  padding-top: 0.4rem;
  margin-top: 0.3rem;
}

.summary-row.total span:last-child {
  color: #1d4ed8;
}

.cart-actions {
  display: flex;
  gap: 0.5rem;
  margin-top: 0.5rem;
}

.btn-cancel {
  padding: 0.5rem 0.75rem;
  background: #e5e7eb;
  color: #374151;
  border: none;
  border-radius: 0.5rem;
  font-size: 0.7rem;
  font-weight: 600;
  cursor: pointer;
}

.btn-cancel:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.btn-pay {
  flex: 1;
  padding: 0.5rem;
  background: #16a34a;
  color: white;
  border: none;
  border-radius: 0.5rem;
  font-size: 0.7rem;
  font-weight: 700;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.3rem;
}

.btn-pay:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.6);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 100;
}

.modal-box {
  background: white;
  border-radius: 1rem;
  box-shadow: 0 25px 50px rgba(0, 0, 0, 0.25);
  width: 100%;
  max-width: 32rem;
  margin: 1rem;
  overflow: hidden;
}

.modal-header {
  padding: 1rem;
  background: linear-gradient(to right, #2563eb, #1d4ed8);
  color: white;
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.modal-header h2 {
  font-weight: 700;
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.close-btn {
  width: 1.75rem;
  height: 1.75rem;
  border-radius: 50%;
  background: rgba(255, 255, 255, 0.2);
  border: none;
  color: white;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
}

.modal-body {
  padding: 1rem;
  max-height: 60vh;
  overflow-y: auto;
}

.payment-total {
  background: #111827;
  color: white;
  border-radius: 0.75rem;
  padding: 1rem;
  text-align: center;
  margin-bottom: 1rem;
}

.payment-total p:first-child {
  font-size: 0.7rem;
  color: #9ca3af;
}

.payment-total .amount {
  font-size: 1.5rem;
  font-weight: 700;
}

.payment-methods {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 0.5rem;
  margin-bottom: 1rem;
}

.method-btn {
  padding: 0.5rem;
  border-radius: 0.5rem;
  border: 2px solid #e5e7eb;
  text-align: center;
  cursor: pointer;
  font-size: 0.7rem;
  font-weight: 500;
  transition: all 0.2s;
}

.method-btn.active {
  border-color: #2563eb;
  background: #eff6ff;
}

.method-btn i {
  color: #2563eb;
  display: block;
  margin-bottom: 0.2rem;
}

.cash-input {
  margin-top: 1rem;
}

.input-wrapper {
  position: relative;
  margin-bottom: 0.75rem;
}

.input-wrapper span {
  position: absolute;
  left: 0.75rem;
  top: 50%;
  transform: translateY(-50%);
  color: #6b7280;
  font-weight: 500;
}

.input-wrapper input {
  width: 100%;
  padding: 0.5rem 0.75rem 0.5rem 2.5rem;
  border: 1px solid #d1d5db;
  border-radius: 0.5rem;
  font-size: 1.2rem;
  font-weight: 700;
  outline: none;
}

.input-wrapper input:focus {
  border-color: #2563eb;
  box-shadow: 0 0 0 2px rgba(37, 99, 235, 0.2);
}

.change-box {
  padding: 0.75rem;
  border-radius: 0.5rem;
  text-align: center;
}

.change-box.success {
  background: #f0fdf4;
  border: 1px solid #bbf7d0;
}

.change-box.danger {
  background: #fef2f2;
  border: 1px solid #fecaca;
}

.change-box p:first-child {
  font-size: 0.7rem;
  color: #4b5563;
}

.change-box .amount {
  font-size: 1.3rem;
  font-weight: 700;
}

.change-box.success .amount {
  color: #16a34a;
}

.change-box.danger .amount {
  color: #dc2626;
}

.modal-footer {
  padding: 1rem;
  border-top: 1px solid #e5e7eb;
  display: flex;
  gap: 0.5rem;
}

.btn-process {
  flex: 1;
  padding: 0.5rem;
  background: #16a34a;
  color: white;
  border: none;
  border-radius: 0.5rem;
  font-size: 0.875rem;
  font-weight: 700;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.3rem;
}

.btn-process:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.receipt-modal {
  max-width: 24rem;
}

.receipt-header {
  background: #16a34a;
  color: white;
  padding: 1rem;
  text-align: center;
}

.success-icon {
  width: 3rem;
  height: 3rem;
  background: rgba(255, 255, 255, 0.2);
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 0 auto 0.5rem;
}

.success-icon i {
  font-size: 1.2rem;
}

.receipt-body {
  padding: 1rem;
}

.receipt {
  border: 2px dashed #d1d5db;
  border-radius: 0.5rem;
  padding: 1rem;
  font-family: 'Courier New', monospace;
  font-size: 0.7rem;
}

.receipt-store {
  text-align: center;
  margin-bottom: 0.5rem;
  padding-bottom: 0.5rem;
  border-bottom: 1px dashed #d1d5db;
}

.store-name {
  font-weight: 700;
  font-size: 0.8rem;
}

.store-address {
  font-size: 0.6rem;
  color: #6b7280;
}

.receipt-info {
  margin-bottom: 0.5rem;
  padding-bottom: 0.5rem;
  border-bottom: 1px dashed #d1d5db;
}

.info-row {
  display: flex;
  justify-content: space-between;
  font-size: 0.6rem;
}

.receipt-items {
  margin-bottom: 0.5rem;
  padding-bottom: 0.5rem;
  border-bottom: 1px dashed #d1d5db;
}

.receipt-item {
  margin-bottom: 0.3rem;
}

.item-name {
  font-size: 0.6rem;
}

.item-detail {
  display: flex;
  justify-content: space-between;
  font-size: 0.55rem;
  color: #6b7280;
}

.receipt-total {
  margin-bottom: 0.5rem;
  padding-bottom: 0.5rem;
  border-bottom: 1px dashed #d1d5db;
}

.total-row {
  display: flex;
  justify-content: space-between;
  font-weight: 700;
  font-size: 0.75rem;
}

.receipt-payment {
  margin-bottom: 0.5rem;
}

.payment-row {
  display: flex;
  justify-content: space-between;
  font-size: 0.6rem;
}

.receipt-footer {
  text-align: center;
  margin-top: 0.5rem;
  padding-top: 0.5rem;
  border-top: 1px dashed #d1d5db;
}

.receipt-footer p {
  font-size: 0.55rem;
  color: #6b7280;
}

.receipt-actions {
  padding: 0.75rem;
  border-top: 1px solid #e5e7eb;
  display: flex;
  gap: 0.5rem;
}

.btn-new {
  flex: 1;
  padding: 0.5rem;
  background: #2563eb;
  color: white;
  border: none;
  border-radius: 0.5rem;
  font-size: 0.875rem;
  font-weight: 600;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.3rem;
}

@media (max-width: 768px) {
  .pos-cart {
    width: 280px;
  }
  
  .product-grid {
    grid-template-columns: repeat(auto-fill, minmax(110px, 1fr));
  }
}
</style>

// src/pages/POSPage.tsx
import React, { useState, useMemo } from 'react';
import { useStore } from '../context/StoreContext';

export default function POSPage() {
  const { products, categories, units, customers, storeSettings, currentUser, addSaleTransaction } = useStore();
  const [search, setSearch] = useState('');
  const [activeCategory, setActiveCategory] = useState('all');
  const [cart, setCart] = useState<Array<{ product: any; quantity: number }>>([]);
  const [selectedCustomerId, setSelectedCustomerId] = useState('c0');
  const [showPaymentModal, setShowPaymentModal] = useState(false);
  const [paymentMethod, setPaymentMethod] = useState('Tunai');
  const [cashInput, setCashInput] = useState('');

  const filteredProducts = useMemo(() => {
    return products.filter(p => {
      if (p.status !== 'active') return false;
      const matchCat = activeCategory === 'all' || p.categoryId === activeCategory;
      const matchSearch = p.name.toLowerCase().includes(search.toLowerCase()) ||
        p.barcode.includes(search) ||
        p.sku.toLowerCase().includes(search.toLowerCase());
      return matchCat && matchSearch;
    });
  }, [products, activeCategory, search]);

  const cartTotalItems = cart.reduce((s, i) => s + i.quantity, 0);
  const cartSubtotal = cart.reduce((s, i) => s + i.product.sellPrice * i.quantity, 0);
  const cartTax = Math.round(cartSubtotal * (storeSettings.taxRate / 100));
  const cartGrandTotal = cartSubtotal + cartTax;

  const cashValue = parseInt(cashInput.replace(/\D/g, '')) || 0;
  const cashChange = cashValue - cartGrandTotal;
  const isPaymentValid = paymentMethod === 'Tunai' ? cashValue >= cartGrandTotal : true;

  const getCategoryIcon = (id: string) => {
    const cat = categories.find(c => c.id === id);
    return cat ? cat.icon : 'fa-box';
  };

  const getCategoryColor = (id: string) => {
    const cat = categories.find(c => c.id === id);
    return cat ? cat.color : '#f3f4f6';
  };

  const getUnitName = (id: string) => {
    const unit = units.find(u => u.id === id);
    return unit ? unit.shortName : '-';
  };

  const getStockBadge = (product: any) => {
    if (product.stock === 0) return 'bg-red-100 text-red-700';
    if (product.stock <= product.minStock) return 'bg-yellow-100 text-yellow-700';
    return 'bg-green-100 text-green-700';
  };

  const formatRupiah = (n: number) => 'Rp ' + (n || 0).toLocaleString('id-ID');

  const addToCart = (product: any) => {
    if (product.stock <= 0) return;
    const existing = cart.find(i => i.product.id === product.id);
    if (existing) {
      if (existing.quantity < product.stock) {
        setCart(cart.map(i => i.product.id === product.id ? { ...i, quantity: i.quantity + 1 } : i));
      }
    } else {
      setCart([...cart, { product: { ...product }, quantity: 1 }]);
    }
  };

  const updateCartQty = (productId: string, delta: number) => {
    const item = cart.find(i => i.product.id === productId);
    if (!item) return;
    const newQty = item.quantity + delta;
    if (newQty <= 0) {
      removeFromCart(productId);
      return;
    }
    if (newQty > item.product.stock) return;
    setCart(cart.map(i => i.product.id === productId ? { ...i, quantity: newQty } : i));
  };

  const removeFromCart = (productId: string) => {
    setCart(cart.filter(i => i.product.id !== productId));
  };

  const clearCart = () => {
    setCart([]);
  };

  const processPayment = () => {
    if (!isPaymentValid || !currentUser) return;
    const change = paymentMethod === 'Tunai' ? cashChange : 0;
    const payment = paymentMethod === 'Tunai' ? cashValue : cartGrandTotal;
    const customer = customers.find(c => c.id === selectedCustomerId);
    
    const transaction = {
      id: 'TX-' + Date.now(),
      invoiceNo: 'INV-' + String(Date.now()).slice(-6),
      items: cart.map(i => ({ product: i.product, quantity: i.quantity, subtotal: i.product.sellPrice * i.quantity })),
      subtotal: cartSubtotal,
      discount: 0,
      tax: cartTax,
      total: cartGrandTotal,
      paymentMethod,
      paymentAmount: payment,
      change,
      customerId: selectedCustomerId,
      customerName: customer?.name || 'Walk-in',
      cashierId: currentUser.id,
      cashierName: currentUser.name,
      date: new Date().toISOString(),
      status: 'completed',
      shiftId: ''
    };

    addSaleTransaction(transaction);
    alert('Transaksi berhasil! Invoice: ' + transaction.invoiceNo);
    setCart([]);
    setCashInput('');
    setShowPaymentModal(false);
  };

  return (
    <div className="h-full flex">
      {/* Left: Products */}
      <div className="flex-1 flex flex-col overflow-hidden">
        <div className="p-3 bg-white border-b shadow-sm">
          <div className="relative mb-2">
            <i className="fas fa-search absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"></i>
            <input
              type="text"
              placeholder="🔍 Scan barcode / Cari produk..."
              value={search}
              onChange={e => setSearch(e.target.value)}
              className="w-full pl-10 pr-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none text-sm"
            />
          </div>
          <div className="flex gap-1.5 overflow-x-auto scrollbar-hide">
            <button
              onClick={() => setActiveCategory('all')}
              className={`px-3 py-1.5 rounded-full text-xs font-medium whitespace-nowrap transition-all ${
                activeCategory === 'all' ? 'bg-blue-600 text-white' : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
              }`}
            >
              <i className="fas fa-border-all mr-1"></i>Semua
            </button>
            {categories.map(cat => (
              <button
                key={cat.id}
                onClick={() => setActiveCategory(cat.id)}
                className={`px-3 py-1.5 rounded-full text-xs font-medium whitespace-nowrap transition-all ${
                  activeCategory === cat.id ? 'bg-blue-600 text-white' : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
                }`}
              >
                <i className={`fas ${cat.icon} mr-1`}></i>{cat.name}
              </button>
            ))}
          </div>
        </div>

        <div className="flex-1 overflow-y-auto p-3">
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-2">
            {filteredProducts.map(product => (
              <button
                key={product.id}
                onClick={() => addToCart(product)}
                disabled={product.stock <= 0}
                className={`group relative bg-white rounded-xl border-2 p-2.5 text-left transition-all hover:shadow-lg hover:-translate-y-0.5 ${
                  product.stock <= 0 ? 'opacity-50 cursor-not-allowed border-gray-200' : 'border-gray-100 hover:border-blue-300'
                }`}
              >
                <div
                  className="w-full aspect-square rounded-lg flex items-center justify-center mb-2"
                  style={{ background: getCategoryColor(product.categoryId) }}
                >
                  <i className={`fas ${getCategoryIcon(product.categoryId)} text-xl`}></i>
                </div>
                <h3 className="text-[11px] font-semibold text-gray-800 line-clamp-2 leading-tight mb-1">{product.name}</h3>
                <p className="text-sm font-bold text-blue-700">{formatRupiah(product.sellPrice)}</p>
                <div className="flex items-center justify-between mt-1">
                  <span className={`text-[9px] px-1.5 py-0.5 rounded-full ${getStockBadge(product)}`}>
                    {product.stock} {getUnitName(product.unitId)}
                  </span>
                  <span className="text-[9px] text-gray-400">{product.sku}</span>
                </div>
              </button>
            ))}
          </div>
          {filteredProducts.length === 0 && (
            <div className="flex flex-col items-center justify-center h-48 text-gray-400">
              <i className="fas fa-search text-4xl mb-3 opacity-30"></i>
              <p className="text-sm">Produk tidak ditemukan</p>
            </div>
          )}
        </div>
      </div>

      {/* Right: Cart */}
      <div className="w-96 bg-white border-l flex flex-col shadow-xl">
        <div className="bg-gradient-to-r from-blue-600 to-blue-700 text-white p-3">
          <div className="flex items-center justify-between mb-1">
            <div className="flex items-center gap-2">
              <i className="fas fa-shopping-cart"></i>
              <h2 className="font-bold text-sm">Keranjang</h2>
            </div>
            <span className="bg-white/20 px-2 py-0.5 rounded-full text-xs">{cartTotalItems} item</span>
          </div>
          <p className="text-xl font-bold">{formatRupiah(cartGrandTotal)}</p>
        </div>

        <div className="p-2 border-b bg-gray-50">
          <select
            value={selectedCustomerId}
            onChange={e => setSelectedCustomerId(e.target.value)}
            className="w-full px-2 py-1.5 text-xs border rounded-lg bg-white"
          >
            {customers.map(c => (
              <option key={c.id} value={c.id}>
                {c.name} {c.isMember ? `(${c.memberCode})` : ''}
              </option>
            ))}
          </select>
        </div>

        <div className="flex-1 overflow-y-auto">
          {cart.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-full text-gray-400 p-6">
              <i className="fas fa-cart-shopping text-4xl mb-3 opacity-30"></i>
              <p className="text-xs font-medium">Keranjang kosong</p>
              <p className="text-[10px] mt-1">Klik produk untuk menambahkan</p>
            </div>
          ) : (
            <div className="divide-y">
              {cart.map(item => (
                <div key={item.product.id} className="p-2.5 hover:bg-gray-50">
                  <div className="flex items-start gap-2">
                    <div className="flex-1 min-w-0">
                      <h4 className="text-xs font-medium text-gray-800 truncate">{item.product.name}</h4>
                      <p className="text-[10px] text-gray-500">{formatRupiah(item.product.sellPrice)} × {item.quantity}</p>
                    </div>
                    <button
                      onClick={() => removeFromCart(item.product.id)}
                      className="text-red-400 hover:text-red-600 text-[10px] p-1"
                    >
                      <i className="fas fa-trash"></i>
                    </button>
                  </div>
                  <div className="flex items-center justify-between mt-1.5">
                    <div className="flex items-center gap-1">
                      <button
                        onClick={() => updateCartQty(item.product.id, -1)}
                        className="w-6 h-6 rounded bg-gray-100 hover:bg-gray-200 flex items-center justify-center text-xs font-bold"
                      >
                        −
                      </button>
                      <span className="w-8 text-center text-xs font-bold">{item.quantity}</span>
                      <button
                        onClick={() => updateCartQty(item.product.id, 1)}
                        disabled={item.quantity >= item.product.stock}
                        className="w-6 h-6 rounded bg-gray-100 hover:bg-gray-200 flex items-center justify-center text-xs font-bold disabled:opacity-50"
                      >
                        +
                      </button>
                    </div>
                    <p className="text-xs font-bold text-blue-700">{formatRupiah(item.product.sellPrice * item.quantity)}</p>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        <div className="border-t bg-gray-50 p-3 space-y-1.5">
          <div className="flex justify-between text-xs">
            <span className="text-gray-600">Subtotal</span>
            <span className="font-medium">{formatRupiah(cartSubtotal)}</span>
          </div>
          <div className="flex justify-between text-xs">
            <span className="text-gray-600">PPN ({storeSettings.taxRate}%)</span>
            <span className="font-medium">{formatRupiah(cartTax)}</span>
          </div>
          <div className="flex justify-between text-base font-bold border-t pt-1.5">
            <span>TOTAL</span>
            <span className="text-blue-700">{formatRupiah(cartGrandTotal)}</span>
          </div>
          <div className="flex gap-2 pt-2">
            <button
              onClick={clearCart}
              disabled={cart.length === 0}
              className="px-3 py-2 bg-gray-200 text-gray-700 rounded-lg font-medium text-xs hover:bg-gray-300 disabled:opacity-50"
            >
              <i className="fas fa-times mr-1"></i>Batal
            </button>
            <button
              onClick={() => setShowPaymentModal(true)}
              disabled={cart.length === 0}
              className="flex-1 py-2 bg-gradient-to-r from-green-500 to-green-600 text-white rounded-lg font-bold text-xs hover:from-green-600 hover:to-green-700 disabled:opacity-50 shadow-lg shadow-green-200"
            >
              <i className="fas fa-credit-card mr-1"></i>BAYAR
            </button>
          </div>
        </div>
      </div>

      {/* Payment Modal */}
      {showPaymentModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm">
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg mx-4 overflow-hidden">
            <div className="bg-gradient-to-r from-blue-600 to-blue-800 text-white p-4">
              <div className="flex items-center justify-between">
                <h2 className="text-lg font-bold"><i className="fas fa-cash-register mr-2"></i>Pembayaran</h2>
                <button onClick={() => setShowPaymentModal(false)} className="w-7 h-7 rounded-full bg-white/20 flex items-center justify-center hover:bg-white/30">
                  <i className="fas fa-times text-sm"></i>
                </button>
              </div>
            </div>
            <div className="p-4">
              <div className="bg-gray-900 text-white rounded-xl p-4 text-center mb-4">
                <p className="text-xs text-gray-300">Total Pembayaran</p>
                <p className="text-2xl font-bold">{formatRupiah(cartGrandTotal)}</p>
              </div>
              <div className="grid grid-cols-3 gap-2 mb-4">
                {['Tunai', 'QRIS', 'Debit', 'E-Wallet', 'Transfer'].map(method => (
                  <button
                    key={method}
                    onClick={() => setPaymentMethod(method)}
                    className={`p-2 rounded-lg border-2 text-xs font-medium transition-all flex flex-col items-center gap-1 ${
                      paymentMethod === method ? 'border-blue-500 bg-blue-50' : 'border-gray-200 hover:border-gray-300'
                    }`}
                  >
                    <i className="fas fa-money-bill-wave text-blue-500"></i>
                    {method}
                  </button>
                ))}
              </div>
              {paymentMethod === 'Tunai' && (
                <>
                  <div className="relative mb-3">
                    <span className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500 font-medium">Rp</span>
                    <input
                      type="text"
                      value={cashInput ? parseInt(cashInput).toLocaleString('id-ID') : ''}
                      onChange={e => setCashInput(e.target.value.replace(/\D/g, ''))}
                      placeholder="0"
                      className="w-full pl-12 pr-4 py-3 border-2 border-gray-300 rounded-xl text-xl font-bold focus:border-blue-500 outline-none"
                      autoFocus
                    />
                  </div>
                  {cashValue > 0 && (
                    <div className={`p-2 rounded-lg text-center ${cashChange >= 0 ? 'bg-green-50 border border-green-200' : 'bg-red-50 border border-red-200'}`}>
                      <p className="text-xs text-gray-600">Kembalian</p>
                      <p className={`text-xl font-bold ${cashChange >= 0 ? 'text-green-600' : 'text-red-600'}`}>
                        {cashChange >= 0 ? formatRupiah(cashChange) : 'Kurang ' + formatRupiah(Math.abs(cashChange))}
                      </p>
                    </div>
                  )}
                </>
              )}
            </div>
            <div className="border-t p-3 flex gap-2">
              <button onClick={() => setShowPaymentModal(false)} className="px-4 py-2.5 bg-gray-200 text-gray-700 rounded-xl font-medium text-sm hover:bg-gray-300">
                Batal
              </button>
              <button
                onClick={processPayment}
                disabled={!isPaymentValid}
                className="flex-1 py-2.5 bg-green-600 text-white rounded-xl font-bold text-sm hover:bg-green-700 disabled:opacity-50"
              >
                <i className="fas fa-check-circle mr-1"></i>Proses Pembayaran
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
